import { ApprovalRequest } from '@/types/approval';

export const mockApprovalRequests: ApprovalRequest[] = [
  {
    id: 'appr-501',
    approvalNumber: 'APR-2024-001',
    type: 'LOAN_ASSESSMENT',
    entityId: 'asm-101',
    status: 'PENDING',
    customerId: 'cust-001',
    customerName: 'Rajesh Kumar',
    customerPhone: '+91 98401 23456',
    requestedAmount: 500000,
    loanType: 'Business Loan',
    tenureMonths: 24,
    assessmentSummary: {
      assessmentId: 'asm-101',
      creditScore: 785,
      foir: 25.0,
      riskBand: 'EXCELLENT',
      monthlyIncome: 100000,
      recommendedRate: 14.5,
      existingObligationsTotal: 30000,
    },
    kycSummary: {
      status: 'VERIFIED',
      verifiedDocsCount: 3,
      totalDocsCount: 3,
      riskCategory: 'LOW',
    },
    staffRemarks: 'Verified turnover of ₹1.2 Cr from GST returns. Storefront owned outright with no hypothecation. Recommending approval at 14.5% p.a.',
    submittedBy: {
      id: 'usr-staff-1',
      name: 'Karthik Raman',
      role: 'Senior Credit Officer',
      submittedAt: '2024-09-18T14:45:00Z',
    },
    auditHistory: [
      {
        id: 'aud-1',
        action: 'SUBMITTED_FOR_APPROVAL',
        performedBy: 'Karthik Raman',
        timestamp: '2024-09-18T14:45:00Z',
        notes: 'Submitted with verified ITR and 6-month bank statement.',
      },
    ],
    createdAt: '2024-09-18T14:45:00Z',
    updatedAt: '2024-09-18T14:45:00Z',
  },
  {
    id: 'appr-502',
    approvalNumber: 'APR-2024-002',
    type: 'LOAN_ASSESSMENT',
    entityId: 'asm-102',
    status: 'APPROVED',
    customerId: 'cust-002',
    customerName: 'Priya Sundaram',
    customerPhone: '+91 97890 54321',
    requestedAmount: 250000,
    loanType: 'Gold Loan',
    tenureMonths: 12,
    assessmentSummary: {
      assessmentId: 'asm-102',
      creditScore: 740,
      foir: 20.0,
      riskBand: 'GOOD',
      monthlyIncome: 75000,
      recommendedRate: 11.5,
      existingObligationsTotal: 0,
    },
    kycSummary: {
      status: 'VERIFIED',
      verifiedDocsCount: 2,
      totalDocsCount: 2,
      riskCategory: 'LOW',
    },
    staffRemarks: 'Assayed gold in branch vault (64.5g). LTV is 64.6%.',
    submittedBy: {
      id: 'usr-staff-2',
      name: 'Ananya Deshmukh',
      role: 'Branch Manager',
      submittedAt: '2024-09-14T10:00:00Z',
    },
    decision: {
      decidedBy: 'usr-admin-1',
      decidedByName: 'S. Narayanan (Managing Director / Owner)',
      decisionDate: '2024-09-15T11:20:00Z',
      decisionRemarks: 'Approved based on verified gold collateral assay and clean repayment history.',
      approvedAmount: 250000,
      interestRateApproved: 11.5,
      specialConditions: ['Gold packet sealed in presence of customer & dual-custody vault keyholder.'],
    },
    auditHistory: [
      {
        id: 'aud-2',
        action: 'SUBMITTED_FOR_APPROVAL',
        performedBy: 'Ananya Deshmukh',
        timestamp: '2024-09-14T10:00:00Z',
      },
      {
        id: 'aud-3',
        action: 'APPROVED_BY_OWNER',
        performedBy: 'S. Narayanan (Owner)',
        timestamp: '2024-09-15T11:20:00Z',
        notes: 'Sanction order released.',
      },
    ],
    createdAt: '2024-09-14T10:00:00Z',
    updatedAt: '2024-09-15T11:20:00Z',
  },
  {
    id: 'appr-503',
    approvalNumber: 'APR-2024-003',
    type: 'LOAN_ASSESSMENT',
    entityId: 'asm-103',
    status: 'CHANGES_REQUESTED',
    customerId: 'cust-003',
    customerName: 'Murugan Palaniswamy',
    customerPhone: '+91 99402 78901',
    requestedAmount: 95000,
    loanType: 'Two-Wheeler Loan',
    tenureMonths: 18,
    assessmentSummary: {
      assessmentId: 'asm-103',
      creditScore: 645,
      foir: 51.4,
      riskBand: 'FAIR',
      monthlyIncome: 35000,
      recommendedRate: 16.0,
      existingObligationsTotal: 14000,
    },
    kycSummary: {
      status: 'VERIFIED',
      verifiedDocsCount: 2,
      totalDocsCount: 3,
      riskCategory: 'MEDIUM',
    },
    staffRemarks: 'Customer is purchase-ready for Royal Enfield 350. FOIR is slightly high at 51.4%.',
    submittedBy: {
      id: 'usr-staff-1',
      name: 'Karthik Raman',
      role: 'Senior Credit Officer',
      submittedAt: '2024-09-19T16:00:00Z',
    },
    decision: {
      decidedBy: 'usr-admin-1',
      decidedByName: 'S. Narayanan (Managing Director / Owner)',
      decisionDate: '2024-09-20T10:30:00Z',
      decisionRemarks: 'FOIR exceeds company guideline of 50%. Require a creditworthy co-guarantor with salary > ₹30,000 before sanction.',
      specialConditions: ['Add co-guarantor KYC and salary slips.'],
    },
    auditHistory: [
      {
        id: 'aud-4',
        action: 'SUBMITTED_FOR_APPROVAL',
        performedBy: 'Karthik Raman',
        timestamp: '2024-09-19T16:00:00Z',
      },
      {
        id: 'aud-5',
        action: 'CHANGES_REQUESTED',
        performedBy: 'S. Narayanan (Owner)',
        timestamp: '2024-09-20T10:30:00Z',
        notes: 'Requested co-guarantor addition.',
      },
    ],
    createdAt: '2024-09-19T16:00:00Z',
    updatedAt: '2024-09-20T10:30:00Z',
  },
  {
    id: 'appr-504',
    approvalNumber: 'APR-2024-004',
    type: 'SETTLEMENT_WAIVER',
    entityId: 'tsk-002',
    status: 'PENDING',
    customerId: 'cust-005',
    customerName: 'Suresh Venkatraman',
    customerPhone: '+91 98840 12345',
    requestedAmount: 18200,
    loanType: 'Gold Loan',
    tenureMonths: 12,
    assessmentSummary: {
      assessmentId: 'asm-105',
      creditScore: 560,
      foir: 84.4,
      riskBand: 'POOR',
      monthlyIncome: 45000,
      recommendedRate: 18.0,
      existingObligationsTotal: 240000,
    },
    kycSummary: {
      status: 'VERIFIED',
      verifiedDocsCount: 2,
      totalDocsCount: 2,
      riskCategory: 'HIGH',
    },
    staffRemarks: 'Customer requests waiver of ₹1,800 overdue penal interest upon upfront payment of principal and regular interest.',
    submittedBy: {
      id: 'usr-staff-1',
      name: 'Karthik Raman',
      role: 'Recovery Specialist',
      submittedAt: '2024-09-23T17:00:00Z',
    },
    auditHistory: [
      {
        id: 'aud-6',
        action: 'WAIVER_REQUEST_SUBMITTED',
        performedBy: 'Karthik Raman',
        timestamp: '2024-09-23T17:00:00Z',
      },
    ],
    createdAt: '2024-09-23T17:00:00Z',
    updatedAt: '2024-09-23T17:00:00Z',
  },
];
