import { LoanAssessment } from '@/types/assessment';

export const mockAssessments: LoanAssessment[] = [
  {
    id: 'asm-101',
    assessmentNumber: 'ASM-2024-0089',
    customerId: 'cust-001',
    customerName: 'Rajesh Kumar',
    customerPhone: '+91 98401 23456',
    loanType: 'BUSINESS',
    requestedAmount: 500000,
    requestedTenureMonths: 24,
    status: 'UNDER_REVIEW',
    creditDetails: {
      score: 785,
      provider: 'CIBIL',
      riskBand: 'EXCELLENT',
      scoreDate: '2024-09-10',
      summary: 'Clean repayment track record across 3 past commercial chit subscriptions and 1 bike loan.',
    },
    eligibility: {
      monthlyIncome: 100000,
      totalMonthlyObligations: 25000,
      foir: 25.0,
      eligibleLoanAmount: 650000,
      maxTenureMonths: 36,
      recommendedInterestRate: 14.5,
      riskScore: 88,
      isEligible: true,
    },
    existingObligations: [
      {
        id: 'ob-1',
        institutionName: 'HDFC Bank',
        loanType: 'Two-Wheeler Loan',
        originalAmount: 85000,
        outstandingBalance: 18000,
        monthlyEmi: 3200,
        status: 'ACTIVE',
      },
      {
        id: 'ob-2',
        institutionName: 'SBI Credit Card',
        loanType: 'Revolving Credit',
        originalAmount: 100000,
        outstandingBalance: 12000,
        monthlyEmi: 1500,
        status: 'ACTIVE',
      },
    ],
    collateralDetails: {
      type: 'Commercial Shop Property Documents',
      description: 'Original deed of retail textile storefront in Anna Nagar West',
      estimatedValue: 1800000,
      ltvPercentage: 27.7,
    },
    supportingDocuments: [
      { id: 'doc-1', name: 'ITR FY2023-24.pdf', type: 'INCOME', verified: true },
      { id: 'doc-2', name: 'Bank Statement 6 Months.pdf', type: 'BANK', verified: true },
      { id: 'doc-3', name: 'GST Certificate.pdf', type: 'BUSINESS', verified: true },
    ],
    assessorId: 'usr-staff-1',
    assessorName: 'Karthik Raman (Senior Credit Officer)',
    assessorRemarks: 'High disposable income merchant. Business turnover verified against GST returns. Recommended for Owner Approval.',
    createdAt: '2024-09-18T10:30:00Z',
    updatedAt: '2024-09-18T14:45:00Z',
  },
  {
    id: 'asm-102',
    assessmentNumber: 'ASM-2024-0090',
    customerId: 'cust-002',
    customerName: 'Priya Sundaram',
    customerPhone: '+91 97890 54321',
    loanType: 'GOLD',
    requestedAmount: 250000,
    requestedTenureMonths: 12,
    status: 'APPROVED',
    creditDetails: {
      score: 740,
      provider: 'EXPERIAN',
      riskBand: 'GOOD',
      scoreDate: '2024-09-12',
      summary: 'Prompt EMI track record. No defaults or 30+ DPD delays in past 36 months.',
    },
    eligibility: {
      monthlyIncome: 75000,
      totalMonthlyObligations: 15000,
      foir: 20.0,
      eligibleLoanAmount: 350000,
      maxTenureMonths: 24,
      recommendedInterestRate: 11.5,
      riskScore: 92,
      isEligible: true,
    },
    existingObligations: [],
    collateralDetails: {
      type: '22K Gold Ornaments',
      description: 'Gold necklace and 4 bangles. Net gold weight: 64.5 grams assayed by certified appraiser.',
      estimatedValue: 387000,
      ltvPercentage: 64.6,
    },
    supportingDocuments: [
      { id: 'doc-4', name: 'Gold Assay Certificate.pdf', type: 'COLLATERAL', verified: true },
      { id: 'doc-5', name: 'Aadhaar Card.pdf', type: 'KYC', verified: true },
    ],
    assessorId: 'usr-staff-2',
    assessorName: 'Ananya Deshmukh',
    assessorRemarks: 'Gold appraised in branch vault. Purity guaranteed at 91.6%. Safe LTV well below 75% regulatory ceiling.',
    ownerApprovalId: 'appr-501',
    createdAt: '2024-09-14T09:15:00Z',
    updatedAt: '2024-09-15T11:20:00Z',
  },
  {
    id: 'asm-103',
    assessmentNumber: 'ASM-2024-0091',
    customerId: 'cust-003',
    customerName: 'Murugan Palaniswamy',
    customerPhone: '+91 99402 78901',
    loanType: 'BIKE',
    requestedAmount: 95000,
    requestedTenureMonths: 18,
    status: 'REQUIRES_MORE_INFO',
    creditDetails: {
      score: 645,
      provider: 'CIBIL',
      riskBand: 'FAIR',
      scoreDate: '2024-09-19',
      summary: 'Recent inquiry count elevated. Prior chit delay noted in Month 4 of 2023.',
    },
    eligibility: {
      monthlyIncome: 35000,
      totalMonthlyObligations: 18000,
      foir: 51.4,
      eligibleLoanAmount: 80000,
      maxTenureMonths: 24,
      recommendedInterestRate: 16.0,
      riskScore: 58,
      isEligible: false,
    },
    existingObligations: [
      {
        id: 'ob-3',
        institutionName: 'Bajaj Finance',
        loanType: 'Consumer Durable',
        originalAmount: 45000,
        outstandingBalance: 14000,
        monthlyEmi: 2800,
        status: 'ACTIVE',
      },
    ],
    collateralDetails: {
      type: 'Hypothecated Two-Wheeler',
      description: 'Royal Enfield Hunter 350 invoice & RTO hypothecation endorsement',
      estimatedValue: 145000,
      ltvPercentage: 65.5,
    },
    supportingDocuments: [
      { id: 'doc-6', name: 'Salary Slip August 2024.pdf', type: 'INCOME', verified: false },
    ],
    assessorId: 'usr-staff-1',
    assessorName: 'Karthik Raman',
    assessorRemarks: 'High FOIR above 50%. A guarantor with CIBIL > 700 or additional co-applicant proof required.',
    createdAt: '2024-09-19T14:00:00Z',
    updatedAt: '2024-09-20T16:30:00Z',
  },
  {
    id: 'asm-104',
    assessmentNumber: 'ASM-2024-0092',
    customerId: 'cust-004',
    customerName: 'Kavitha Balakrishnan',
    customerPhone: '+91 94443 67890',
    loanType: 'PERSONAL',
    requestedAmount: 150000,
    requestedTenureMonths: 12,
    status: 'DRAFT',
    creditDetails: {
      score: 710,
      provider: 'CIBIL',
      riskBand: 'GOOD',
      scoreDate: '2024-09-21',
      summary: 'Regular salaried professional. Consistent EPF contribution.',
    },
    eligibility: {
      monthlyIncome: 65000,
      totalMonthlyObligations: 12000,
      foir: 18.5,
      eligibleLoanAmount: 220000,
      maxTenureMonths: 24,
      recommendedInterestRate: 13.5,
      riskScore: 79,
      isEligible: true,
    },
    existingObligations: [],
    supportingDocuments: [],
    assessorId: 'usr-staff-2',
    assessorName: 'Ananya Deshmukh',
    assessorRemarks: 'Application initialized. Awaiting final Form 16 upload.',
    createdAt: '2024-09-21T11:00:00Z',
    updatedAt: '2024-09-21T11:00:00Z',
  },
  {
    id: 'asm-105',
    assessmentNumber: 'ASM-2024-0093',
    customerId: 'cust-005',
    customerName: 'Suresh Venkatraman',
    customerPhone: '+91 98840 12345',
    loanType: 'BUSINESS',
    requestedAmount: 1200000,
    requestedTenureMonths: 36,
    status: 'REJECTED',
    creditDetails: {
      score: 560,
      provider: 'CIBIL',
      riskBand: 'POOR',
      scoreDate: '2024-09-05',
      summary: 'Multiple write-offs and active settlements on unsecured credit lines.',
    },
    eligibility: {
      monthlyIncome: 45000,
      totalMonthlyObligations: 38000,
      foir: 84.4,
      eligibleLoanAmount: 0,
      maxTenureMonths: 12,
      recommendedInterestRate: 24.0,
      riskScore: 22,
      isEligible: false,
    },
    existingObligations: [
      {
        id: 'ob-4',
        institutionName: 'Axis Bank',
        loanType: 'Personal Loan',
        originalAmount: 300000,
        outstandingBalance: 240000,
        monthlyEmi: 11000,
        status: 'DEFAULTED',
      },
    ],
    supportingDocuments: [],
    assessorId: 'usr-staff-1',
    assessorName: 'Karthik Raman',
    assessorRemarks: 'High default risk. Active delinquency on bureau. Assessment closed as rejected.',
    createdAt: '2024-09-05T09:00:00Z',
    updatedAt: '2024-09-06T15:00:00Z',
  },
];
