import { DocumentItem } from '@/types/document';

export const mockDocuments: DocumentItem[] = [
  {
    id: "doc-001",
    customerId: "cust-001",
    customerName: "Rajesh Kumar",
    type: "IDENTITY_PROOF",
    title: "Aadhaar Card Front & Back",
    fileName: "aadhaar_rajesh_kumar.pdf",
    fileSize: 1420000,
    mimeType: "application/pdf",
    fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    status: "VERIFIED",
    uploadedAt: "2024-01-14T10:15:00Z",
    verifiedAt: "2024-01-15T10:30:00Z",
    verifiedBy: "Admin - Suresh",
  },
  {
    id: "doc-002",
    customerId: "cust-001",
    customerName: "Rajesh Kumar",
    type: "ADDRESS_PROOF",
    title: "TNEB Electricity Bill (Latest)",
    fileName: "electricity_bill_annanagar.pdf",
    fileSize: 850000,
    mimeType: "application/pdf",
    fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    status: "VERIFIED",
    uploadedAt: "2024-01-14T10:20:00Z",
    verifiedAt: "2024-01-15T10:32:00Z",
    verifiedBy: "Admin - Suresh",
  },
  {
    id: "doc-003",
    customerId: "cust-001",
    customerName: "Rajesh Kumar",
    type: "PHOTO",
    title: "Passport Size Photograph",
    fileName: "rajesh_photo_passport.jpg",
    fileSize: 320000,
    mimeType: "image/jpeg",
    fileUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    status: "VERIFIED",
    uploadedAt: "2024-01-14T10:22:00Z",
    verifiedAt: "2024-01-15T10:35:00Z",
    verifiedBy: "Admin - Suresh",
  },
  {
    id: "doc-004",
    customerId: "cust-001",
    customerName: "Rajesh Kumar",
    type: "SIGNATURE",
    title: "Specimen Signature Card",
    fileName: "rajesh_signature.png",
    fileSize: 110000,
    mimeType: "image/png",
    fileUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Signature_sample.svg",
    status: "VERIFIED",
    uploadedAt: "2024-01-14T10:25:00Z",
    verifiedAt: "2024-01-15T10:36:00Z",
    verifiedBy: "Admin - Suresh",
  },
  {
    id: "doc-005",
    customerId: "cust-004",
    customerName: "Ananya Deshmukh",
    type: "IDENTITY_PROOF",
    title: "PAN Card Copy",
    fileName: "pan_ananya_deshmukh.jpg",
    fileSize: 490000,
    mimeType: "image/jpeg",
    fileUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80",
    status: "PENDING",
    uploadedAt: "2024-09-15T15:35:00Z",
  },
  {
    id: "doc-006",
    customerId: "cust-004",
    customerName: "Ananya Deshmukh",
    type: "INCOME_PROOF",
    title: "ITR Acknowledgement AY 2024-25",
    fileName: "itr_v_ay2024_ananya.pdf",
    fileSize: 1850000,
    mimeType: "application/pdf",
    fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    status: "PENDING",
    uploadedAt: "2024-09-15T15:40:00Z",
  },
  {
    id: "doc-007",
    customerId: "cust-003",
    customerName: "Murugan Palaniswamy",
    type: "COLLATERAL_DOCUMENT",
    title: "Guarantor Net Worth Certificate",
    fileName: "guarantor_cert_sivakumar.pdf",
    fileSize: 1200000,
    mimeType: "application/pdf",
    fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    status: "VERIFIED",
    uploadedAt: "2024-01-16T12:00:00Z",
    verifiedAt: "2024-01-18T16:00:00Z",
    verifiedBy: "Admin - Suresh",
    relatedEntity: {
      entityType: "LOAN",
      entityId: "loan-203",
    }
  },
  {
    id: "doc-008",
    customerId: "cust-006",
    customerName: "Karthik Subramanian",
    type: "ADDRESS_PROOF",
    title: "Rental Agreement (Old)",
    fileName: "rental_agreement_2022.pdf",
    fileSize: 2100000,
    mimeType: "application/pdf",
    fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    status: "REJECTED",
    rejectionReason: "Agreement expired over 18 months ago. Please submit current rental agreement or registered deed.",
    uploadedAt: "2024-03-12T11:00:00Z",
    verifiedAt: "2024-03-13T14:30:00Z",
    verifiedBy: "Staff - Anand S",
  }
];
