import { NotificationItem } from '@/types/notification';

export const mockNotifications: NotificationItem[] = [
  {
    id: "notif-001",
    title: "Overdue Loan Payment Alert",
    message: "Loan GL-2024-0145 for Karthik Subramanian is 19 days overdue. ₹13,260 pending.",
    type: "OVERDUE_ALERT",
    priority: "HIGH",
    isRead: false,
    link: "/loans/loan-205",
    relatedEntityId: "loan-205",
    createdAt: "2024-09-24T08:30:00Z",
  },
  {
    id: "notif-002",
    title: "Chit Auction Scheduled Today",
    message: "Monthly auction for 'Royal Wealth 5 Lakh Scheme' (CFT-500K-20M) at 4:00 PM.",
    type: "CHIT_AUCTION",
    priority: "HIGH",
    isRead: false,
    link: "/chits/chit-101",
    relatedEntityId: "chit-101",
    createdAt: "2024-09-24T09:00:00Z",
  },
  {
    id: "notif-003",
    title: "Upcoming Payment Due Tomorrow",
    message: "Venkatesh Natarajan has a chit installment of ₹46,500 due on 25-Sep-2024.",
    type: "UPCOMING_PAYMENT",
    priority: "MEDIUM",
    isRead: false,
    link: "/payments",
    relatedEntityId: "pay-506",
    createdAt: "2024-09-23T16:45:00Z",
  },
  {
    id: "notif-004",
    title: "Pending KYC Verification",
    message: "New customer Ananya Deshmukh submitted KYC documents requiring verification.",
    type: "KYC_PENDING",
    priority: "MEDIUM",
    isRead: true,
    link: "/customers/cust-004/documents",
    relatedEntityId: "cust-004",
    createdAt: "2024-09-22T11:20:00Z",
  },
  {
    id: "notif-005",
    title: "Loan Application Submitted",
    message: "New Nominee Loan NL-2024-0019 awaiting credit committee approval.",
    type: "LOAN_APPROVAL",
    priority: "MEDIUM",
    isRead: true,
    link: "/loans/loan-204",
    relatedEntityId: "loan-204",
    createdAt: "2024-09-21T14:10:00Z",
  },
  {
    id: "notif-006",
    title: "System Backup Successful",
    message: "Daily encrypted ledger snapshot archived to cold vault at 03:00 AM.",
    type: "SYSTEM",
    priority: "LOW",
    isRead: true,
    createdAt: "2024-09-24T03:05:00Z",
  }
];
